name: Тестирование

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        oscript_version: ['default', 'stable', 'dev']
        include:
          - oscript_version: 'dev'
            test_engiene: 'oneunit'

    uses: autumn-library/workflows/.github/workflows/test.yml@oneunit
    with:
      oscript_version: ${{ matrix.oscript_version }}
      test_engine: ${{ matrix.test_engiene }}
